<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checklist_pwd_ver_at_least_one</name>
   <tag></tag>
   <elementGuidId>028ca4bd-1144-478d-a622-a0ebde952097</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul[class=&quot;list-checked&quot;]>li[class=&quot;is-checked&quot;]>span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
