<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Check_box_Allow</name>
   <tag></tag>
   <elementGuidId>d296667b-7a3d-469c-983d-c6bed82755ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label[id=&quot;user_register_form_consents_choice_0_label&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
