<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Show_More_button</name>
   <tag></tag>
   <elementGuidId>af319f49-ac4a-4d6f-9a70-f059d340bacb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>md-switch[aria-checked=&quot;false&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
